### ISSUE TITLE
ExFilePicker causing out of memory and crash when fast scrolling up and down in the file list

### ISSUE THREAD

**Issue by helloray** [bartwell/ExFilePicker#11]
With ExFilePickerSample, it will not happen. However, when added into my project, it will easily meet out of memory issue when fast scrolling up and down in the file list view. Tried with similiar project https://github.com/ingyesid/simple-file-chooser, it works OK with my project, no crash, no OOM.

**Comment by bartwell** [comment]
Please, provide test project, where I can to reproduce it.

**Comment by helloray** [comment]
I found I can also duplicate it with ExFilePickerSample. Try to open a directory with many sub-directories(over 500+), then fast scrolling up and down . You will find the UI become very lag. After a while, the app will crash with OOM.

**Comment by bartwell** [comment]
Fixed in version 2.1.
