### ISSUE TITLE
Больше иконок :3

### ISSUE THREAD

**Issue by Romanzi** [bartwell/ExFilePicker#13]
Добавь иконки для книг, архивов, видео, музыки и apk-файлов. А то как-то уныло)

P.S. Да, знаю, глуповато, но сразу как-то красочнее станет)

**Comment by bartwell** [comment]
Думаю, это не является первоочередной задачей. Кроме того, есть определенные сомнения, поскольку нужно будет выбирать иконки с подходящими авторскими правами, а это может быть проблематичным. И увеличится размер библиотеки, притом, что до конца непонятно, нужен ли такой функционал другим пользователям библиотеки. Если идея массово поддержится другими пользователями, можно будет реализовать в будущем.
