### ISSUE TITLE
This directory is empty issue

### ISSUE THREAD

**Issue by alirezasbri** [bartwell/ExFilePicker#19]
I'm using this library in my project, but when the file chooser activity is launched in its root directory (which in my case it is: '/storage/emulated/0/') I get the following error:
"This directory is empty" message.

**Comment by bartwell** [comment]
It should be resolved in version 2.0.

**Comment by hazexzo** [comment]
Проблема по прежнему присутствует в версии 2.1 и в тестовом приложении.
При выходе из /storage/emulated/0 и повтором входе туда же пишет "Эта папка пуста". Как фиксить?

**Comment by hazexzo** [comment]
Так же пропал метод setHideHiddenFilesEnabled.
