### ISSUE TITLE
Save as dialog

### ISSUE THREAD

**Issue by pylerSM** [bartwell/ExFilePicker#23]
Hello, 

Can you provide "Save as" dialog?

Thanks

**Comment by bartwell** [comment]
Hello! Do you have an idea how it should look?

**Comment by bartwell** [comment]
Hello @pylerSM, alternatively you can create your own activity or dialog with EditText for file name and button to call ExFilePicker for directory choose. In this case you can use methods setCanChooseOnlyOneItem() and setChoiceType(ChoiceType.DIRECTORIES);
Please feel free to re-open this issue if you want to suggest another solution.
