### ISSUE TITLE
Configuration didn't take effect

### ISSUE THREAD

**Issue by Cloundhub** [bartwell/ExFilePicker#25]
This function  'setNewFolderButtonDisabled()','setSortButtonDisabled()' didn't take effect when I set the value ‘true’,the button is still on the toolbar. how to solve this problem? Thank u!

**Comment by bartwell** [comment]
Hi @Cloundhub, is it reproducing on [sample application](https://github.com/bartwell/ExFilePicker/tree/master/sample/build/outputs/apk/sample-debug.apk)? I am trying to test it by launch sample application from Android Studio, but this issue doesn't reproduce and this buttons works well.

**Comment by Cloundhub** [comment]
Thank u,I made a mistake that I call functions after star the ExFilePicker. 
But I have another problem that when I press the back key,I just want to back the  'emulated/0/' not the root path

**Comment by bartwell** [comment]
As I understand EFP starting on your device with initial path `/sdcard/`. You can set your own initial path to `/emulated/0/sdcard/` with method `setStartDirectory()`. But please make sure that this way will work well on every device.

**Comment by Cloundhub** [comment]
ok,thank u!
