### ISSUE TITLE
Ошибка "Эта папка пуста"

### ISSUE THREAD

**Issue by hazexzo** [bartwell/ExFilePicker#27]
Проблема, описанная тут - https://github.com/bartwell/ExFilePicker/issues/19, актуальна и версии 2.3.
При выходе из /storage/emulated/0 и повтором входе туда же пишет "Эта папка пуста".

**Comment by bartwell** [comment]
Вероятнее всего, на папку emulated установлены права доступа, которые запрещают приложению чтение содержимого папки. Таким образом, эта проблема должна проявляться и в других приложениях. Исправить это не представляется возможным.

**Comment by hazexzo** [comment]
Ладно. Другой вопрос. Пользователь выбирает файл/ы и выполняется метод А, а если пользователь выбирает папку, выполняется метод B. Возможно ли как-то получить информацию о выбранном?

**Comment by bartwell** [comment]
Закрою как решенный. При необходимости, переоткройте.
