### ISSUE TITLE
Fragment receives no result

### ISSUE THREAD

**Issue by redwolf2** [bartwell/ExFilePicker#28]
Fragments have a method onActivityResult(). This is not called, when you call 

```
ExFilePicker exFilePicker = new ExFilePicker();
exFilePicker.start(getActivity(), REQUEST_CODE_EXPORT_FILE);
```

inside the Fragment. Instead, only the Activity receives the onActivityResult(). You should provide a seperate overload of the start method, that takes a Fragment, instead of an Activity.

https://stackoverflow.com/questions/6147884/onactivityresult-is-not-being-called-in-fragment

Here is the fix:
```
public void start(@NonNull Fragment fragment, int requestCode) {
        Intent intent = new Intent(fragment.getActivity(), ExFilePickerActivity.class);
        intent.putExtra(ExFilePickerActivity.EXTRA_CAN_CHOOSE_ONLY_ONE_ITEM, mCanChooseOnlyOneItem);
        intent.putExtra(ExFilePickerActivity.EXTRA_SHOW_ONLY_EXTENSIONS, mShowOnlyExtensions);
        intent.putExtra(ExFilePickerActivity.EXTRA_EXCEPT_EXTENSIONS, mExceptExtensions);
        intent.putExtra(ExFilePickerActivity.EXTRA_IS_NEW_FOLDER_BUTTON_DISABLED, mIsNewFolderButtonDisabled);
        intent.putExtra(ExFilePickerActivity.EXTRA_IS_SORT_BUTTON_DISABLED, mIsSortButtonDisabled);
        intent.putExtra(ExFilePickerActivity.EXTRA_IS_QUIT_BUTTON_ENABLED, mIsQuitButtonEnabled);
        intent.putExtra(ExFilePickerActivity.EXTRA_CHOICE_TYPE, mChoiceType);
        intent.putExtra(ExFilePickerActivity.EXTRA_SORTING_TYPE, mSortingType);
        intent.putExtra(ExFilePickerActivity.EXTRA_START_DIRECTORY, mStartDirectory);
        intent.putExtra(ExFilePickerActivity.EXTRA_USE_FIRST_ITEM_AS_UP_ENABLED, mUseFirstItemAsUpEnabled);
        intent.putExtra(ExFilePickerActivity.EXTRA_HIDE_HIDDEN_FILES, mHideHiddenFilesEnabled);
        fragment.startActivityForResult(intent, requestCode);
    }
```

**Comment by bartwell** [comment]
I add this method. Please check it in version 2.4.
Thank you for bug report.

**Comment by redwolf2** [comment]
Nice job. Sry I meant android.app.Fragment instead of android.support.v4.app.Fragment. But if you wan't to support it, you have to use min api level 11. Maybe, you could instead provide a way to get the intent.

**Comment by bartwell** [comment]
I add method start() which takes android.app.Fragment as parameter. Please check it on updated library.

**Comment by redwolf2** [comment]
Thank you very much, will do.

**Comment by npes87184** [comment]
Hi,

Does get result from android.app.Fragment is included in 2.4?

Thanks.

**Comment by bartwell** [comment]
Hi @npes87184, yes, it should be included. If you have some troubles with it, please let me know.

**Comment by redwolf2** [comment]
I tried it out. It does not seem to be included in 2.4 on maven, yet.

**Comment by npes87184** [comment]
Hi, @bartwell, can you provide start from android.app.Fragment on maven? thanks.

**Comment by bartwell** [comment]
Hi @npes87184, sorry for delay. I update library on Maven. It should be updated in few hours.

**Comment by npes87184** [comment]
Hi, @bartwell 

In [Maven](https://mvnrepository.com/artifact/ru.bartwell/exfilepicker), it still shows version 2.4 and update date is (Jul, 2017).

I missed something?

Thanks.

**Comment by bartwell** [comment]
Hi @npes87184! I just change version code (not version name) and re-upload it. I think it should updated.

**Comment by HackerOO7** [comment]
@bartwell  In Maven, the version 2.4 is still old version, no `android.app.Fragment`.

**Comment by siyuhong** [comment]
You can see my blog：what to uese ExFilePicker in Fragment？
https://blog.csdn.net/weixin_40774605/article/details/104409843
